package com.cmp;

public enum MenuItem {
	INDEX,
	SHARE_FILE,
	PERSONAL_INFO, 
	VISIT_INFO_NEW,
	VISIT_INFO,
	SALON_INFO,
	PRODUCT_INFO,
	MY_USER, 
	MY_CUST, 
	ADMIN_USER, 
	ADMIN_CUST, 
	ADMIN_ROLE, 
	ADMIN_STATUS, 
	ADMIN_REGISTRATION, 
	API_MAIN, 
	API_MANAGE, 
	CUST_LIST,
	MANAGE_BILLBOARD,
	MANAGE_PRODUCT_FILE,
	MANAGE_REFERENCE_FILE
	
}